### ISSUE TITLE
Project incorrectly structured

### ISSUE THREAD

**Issue by aangar** [WVU-CS230-2024-01-Group02/WVURide#1]
there's a few issues with the structure of this project. here's what needs to be done:

1. remove `node_modules` from the top-level directory. it should NEVER be added in a project as it is a massive data hog, and should be reinstalled each time it is cloned!
2. move all files from `wvuride` to the top level, .gitignore is VERY important!

**Comment by narogeby** [comment]
Thank you. Should be all fixed now.
